### ISSUE TITLE
Thank you for your nice work. May I know when the code will be released

### ISSUE THREAD

**Issue by zgj77** [Zhaozixiang1228/MMIF-DDFM#1]
Thank you for your nice work. May I know when the code will be released

**Comment by Zhaozixiang1228** [comment]
August or September when I'm ready for my camera ready version.

**Comment by linshenj** [comment]
您的工作太棒了，我对您的工作很感兴趣

**Comment by 578578wu** [comment]
作者您好，请问现在发布代码了吗

**Comment by Zhaozixiang1228** [comment]
Thank you for your attention; the code has been released.
