### ISSUE TITLE
关于对比实验

### ISSUE THREAD

**Issue by 19958595306** [Zhaozixiang1228/MMIF-DDFM#21]
赵博士您好，感谢您优秀的工作。对于对比实验部分我有一些问题，我发现对比实验中有些模型的结果与被对比的原论文不同，如TarD模型在您之前的工作CDDFause中在TNO上的SD为45.63，而在本文中为49.89，均与原文51.352不同。我想知道为什么会不一样，谢谢您

**Comment by Zhaozixiang1228** [comment]
您好

可能是指标计算方法或者计算平台（python、matlab）的区别，也有可能测试集图像用的不同，因此可能出现误差。不过我们保证每篇文章中我们的实验设置是公平的

感谢您对我工作的关注
