### ISSUE TITLE
ask for code

### ISSUE THREAD

**Issue by Jiaxin-lucky** [Zhaozixiang1228/MMIF-DDFM#4]
hi, your work is beautiful, may i ask for the code?

**Comment by Zhaozixiang1228** [comment]
Thank you for your attention; the code has been released.

**Comment by Jiaxin-lucky** [comment]
it’s so nice of you, thanks a lot!发自我的 iPhone在 2023年9月29日，16:26，Zixiang Zhao ***@***.***> 写道：﻿
Thank you for your attention; the code has been released.
