### ISSUE TITLE
训练方法

### ISSUE THREAD

**Issue by yehaowei** [Zhaozixiang1228/MMIF-DDFM#6]
能问下大哥训练方法什么时候放出来吗

**Comment by Zhaozixiang1228** [comment]
同学，请认真阅读文章，本方法无需训练。直接用pre-train model即可完成inference

**Comment by linshenj** [comment]
爹，那这个推理时间是就这么长吗，这是不是ddpm的缺陷

**Comment by yehaowei** [comment]
> 爹，那这个推理时间是就这么长吗，这是不是ddpm的缺陷

代码里用的DDIM，已经算快了。我的理解是model 采样过程中eval 没有权重的话 等于线性融合

**Comment by Zhaozixiang1228** [comment]
DDPM采样需要的时间就是比较久，贝叶斯修正模块几乎不需要花费时间，主要时间还是花在了采样上
