### ISSUE TITLE
训练

### ISSUE THREAD

**Issue by SUT-pxc** [Zhaozixiang1228/MMIF-DDFM#7]
学长，我用的是3080的显卡，显存爆了，RuntimeError: CUDA out of memory. Tried to allocate 12.50 GiB (GPU 0; 10.00 GiB total capacity; 7.51 GiB already allocated; 0 bytes free; 8.42 GiB reserved in total by PyTorch)，请问怎么修改才能跑起来啊

**Comment by Zhaozixiang1228** [comment]
这个我也没什么办法。我们的实验是在3090上完成的。
